/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import carrental.Car;
import carrental.Client;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class ClienteInterface extends javax.swing.JFrame {
    private Client cli;

    /**
     * Creates new form ClienteInterface
     */
    public ClienteInterface(Client cli) {
        this.cli=cli;
        initComponents();
    }
    
    public void setCars(ArrayList <Car> c){  
        for(Car oc:c){
            this.Carro.addItem(oc.getName());
        }   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DataInicio = new javax.swing.JFormattedTextField();
        HoraInicio = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        DataTermino = new javax.swing.JFormattedTextField();
        HoraTermino = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        IdadeDoCondutor = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        NumeroCartao = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        NameOnCard = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        MesVencimento = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        AnoVencimento = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        CodigoDeSeguranca = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        Carro = new javax.swing.JComboBox();
        LocalRetirada = new javax.swing.JComboBox();
        LocalDevolucao = new javax.swing.JComboBox();
        Consultar = new javax.swing.JButton();
        Interesse = new javax.swing.JButton();
        Alugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        jLabel1.setText("Local de retirada do veículo:");

        jLabel2.setText("Local de devolução do veículo:");

        jLabel4.setText("Data e horário de inicio:");

        try {
            DataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataInicioActionPerformed(evt);
            }
        });

        try {
            HoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Data e horário de término:");

        try {
            DataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DataTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataTerminoActionPerformed(evt);
            }
        });

        try {
            HoraTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Idade do condutor:");

        IdadeDoCondutor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        IdadeDoCondutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdadeDoCondutorActionPerformed(evt);
            }
        });

        jLabel7.setText("anos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cartão"));

        jLabel9.setText("Número do Cartão:");

        try {
            NumeroCartao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Nome (impresso no cartão):");

        jLabel11.setText("Vencimento do cartão:");

        MesVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM"))));
        MesVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesVencimentoActionPerformed(evt);
            }
        });

        jLabel12.setText("/");

        AnoVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yy"))));

        jLabel13.setText("Código de segurança:");

        try {
            CodigoDeSeguranca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CodigoDeSeguranca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoDeSegurancaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MesVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AnoVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CodigoDeSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NumeroCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CodigoDeSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(MesVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AnoVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(NameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel14.setText("Carro:");

        LocalRetirada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rio de Janeiro", "São Paulo", "Curitiba", "Salvador" }));

        LocalDevolucao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rio de Janeiro", "São Paulo", "Curitiba", "Salvador" }));

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Interesse.setText("Registrar Interesse");
        Interesse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InteresseActionPerformed(evt);
            }
        });

        Alugar.setText("Alugar");
        Alugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DataTermino, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(DataInicio))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(HoraTermino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IdadeDoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LocalDevolucao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LocalRetirada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Carro, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel8)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Interesse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(Alugar)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Carro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LocalRetirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LocalDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(DataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoraTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(IdadeDoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultar)
                    .addComponent(Interesse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Alugar)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataInicioActionPerformed

    private void IdadeDoCondutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdadeDoCondutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdadeDoCondutorActionPerformed

    private void MesVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesVencimentoActionPerformed

    private void CodigoDeSegurancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoDeSegurancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoDeSegurancaActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        String car =(String) this.Carro.getSelectedItem();
        String pickupPlace = (String) this.LocalRetirada.getSelectedItem();
        String dropOffPlace = (String) this.LocalDevolucao.getSelectedItem();
        
        String pickUpSplit [] = this.DataInicio.getText().split("/");
        int yearPick =Integer.parseInt( pickUpSplit[2]);
        yearPick+=1900;
        int monthPick =Integer.parseInt( pickUpSplit[1]);
        int dayPick =Integer.parseInt( pickUpSplit[0]);
        String pickUpSplit2 []=this.HoraInicio.getText().split(":");
        int minutePick =Integer.parseInt( pickUpSplit2[1]);
        int hourPick =Integer.parseInt( pickUpSplit2[0]);
        Date pickUpDate = new Date(yearPick,monthPick,dayPick,hourPick,minutePick);
        
        String dropOffSplit [] = this.DataTermino.getText().split("/");
        int yearDrop =Integer.parseInt( dropOffSplit[2]);
        yearDrop+=1900;
        int monthDrop =Integer.parseInt( dropOffSplit[1]);
        int dayDrop =Integer.parseInt( dropOffSplit[0]);
        String dropOffSplit2 []=this.HoraTermino.getText().split(":");
        int minuteDrop =Integer.parseInt( dropOffSplit2[1]);
        int hourDrop =Integer.parseInt( dropOffSplit2[0]);
        Date dropOffDate = new Date(yearDrop,monthDrop,dayDrop,hourDrop,minuteDrop);
        //String car, String pickUpPlace, String dropOffPlace, Date pickUpDate, Date dropOfDate
        double rate = cli.checkAvailabilityServer(car, pickupPlace, dropOffPlace, pickUpDate, dropOffDate);
        double dias = this.diferencaEmDias(dropOffDate, dropOffDate);
        int diasInt=(int) Math.ceil(dias);
        double preco = rate*diasInt;
        JOptionPane.showMessageDialog(this,"A locação de carro ficará em $" +preco +"","Valor da Consulta",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ConsultarActionPerformed

    private void InteresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InteresseActionPerformed
        // TODO add your handling code here:
        String car = (String) this.Carro.getSelectedItem();
        cli.subscribeCarServer(car);
    }//GEN-LAST:event_InteresseActionPerformed

    private void DataTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataTerminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataTerminoActionPerformed

    private void AlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlugarActionPerformed
        // TODO add your handling code here:
        String car =(String) this.Carro.getSelectedItem();
        String pickupPlace = (String) this.LocalRetirada.getSelectedItem();
        String dropOffPlace = (String) this.LocalDevolucao.getSelectedItem();
        
        String pickUpSplit [] = this.DataInicio.getText().split("/");
        int yearPick =Integer.parseInt( pickUpSplit[2]);
        yearPick-=1900;
        int monthPick =Integer.parseInt( pickUpSplit[1])-1;
        int dayPick =Integer.parseInt( pickUpSplit[0]);
        String pickUpSplit2 []=this.HoraInicio.getText().split(":");
        int minutePick =Integer.parseInt( pickUpSplit2[1]);
        int hourPick =Integer.parseInt( pickUpSplit2[0]);
        Date pickUpDate = new Date(yearPick,monthPick,dayPick,hourPick,minutePick);
        
        String dropOffSplit [] = this.DataTermino.getText().split("/");
        int yearDrop =Integer.parseInt( dropOffSplit[2]);
        yearDrop-=1900;
        int monthDrop =Integer.parseInt( dropOffSplit[1])-1;
        int dayDrop =Integer.parseInt( dropOffSplit[0]);
        String dropOffSplit2 []=this.HoraTermino.getText().split(":");
        int minuteDrop =Integer.parseInt( dropOffSplit2[1]);
        int hourDrop =Integer.parseInt( dropOffSplit2[0]);
        Date dropOffDate = new Date(yearDrop,monthDrop,dayDrop,hourDrop,minuteDrop);
        
        int driveAge = Integer.parseInt(this.IdadeDoCondutor.getText());
        String ccNumber = this.NumeroCartao.getText();
        String ccCode = this.CodigoDeSeguranca.getText();
        String ccName = this.NameOnCard.getText();
        String ccExpDate = this.MesVencimento.getText() +"/" +this.AnoVencimento.getText();
        cli.rentACarServer(car, pickupPlace, dropOffPlace, pickUpDate, dropOffDate, driveAge, ccNumber, ccCode, ccName, ccExpDate);
        //String car, String pickUpPlace, String dropOffPlace, Date pickUpDate, Date dropOfDate, int driverAge,
            //String ccNumber, String ccCode, String ccName, String ccExpDate
    }//GEN-LAST:event_AlugarActionPerformed

    public double diferencaEmDias(Date dataInicial, Date dataFinal){  
        double result = 0;  
        long diferenca = dataFinal.getTime() - dataInicial.getTime();  
        double diferencaEmDias = (diferenca /1000) / 60 / 60 /24; //resultado é diferença entre as datas em dias  
        long horasRestantes = (diferenca /1000) / 60 / 60 %24; //calcula as horas restantes  
        result = diferencaEmDias + (horasRestantes /24d); //transforma as horas restantes em fração de dias  
      
        return result;  
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ClienteInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alugar;
    private javax.swing.JFormattedTextField AnoVencimento;
    private javax.swing.JComboBox Carro;
    private javax.swing.JFormattedTextField CodigoDeSeguranca;
    private javax.swing.JButton Consultar;
    private javax.swing.JFormattedTextField DataInicio;
    private javax.swing.JFormattedTextField DataTermino;
    private javax.swing.JFormattedTextField HoraInicio;
    private javax.swing.JFormattedTextField HoraTermino;
    private javax.swing.JFormattedTextField IdadeDoCondutor;
    private javax.swing.JButton Interesse;
    private javax.swing.JComboBox LocalDevolucao;
    private javax.swing.JComboBox LocalRetirada;
    private javax.swing.JFormattedTextField MesVencimento;
    private javax.swing.JTextField NameOnCard;
    private javax.swing.JFormattedTextField NumeroCartao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
